// <auto-generated />
using CodeFirst_Revize.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeFirst_Revize.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst_Revize.Data.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("Yapildi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Gorevler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Tatile çık",
                            Yapildi = false
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Evlen",
                            Yapildi = false
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Saygınlık kazan",
                            Yapildi = true
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "İşe Gir",
                            Yapildi = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
